const UrlConfig = {
	profile: {
		myProfile: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/my-profile`,
		changePassword: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/my-profile/change-password`,
		myAvatar: `${process.env.NEXT_APP_IOT_DOMAIN}/api/account/profile-picture-file`,
		uploadAvatarBase64: `${process.env.NEXT_APP_IOT_DOMAIN}/api/account/profile-picture`,
		twoFactor: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/my-profile/two-factor-enabled`,
		setTwoFactor: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/my-profile/set-two-factor-enabled`,
	},
	auth: {
		getXSRFToken: `${process.env.NEXT_APP_IOT_DOMAIN}/abp/Swashbuckle/SetCsrfCookie`,
	},
	userManagement: {
		getUserProfile: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/users/`,
		getUserByUsername: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/users/by-username/`,
		getUser: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/users?MaxResultCount=100`,
		getRoleOfUser: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/users/`,
		deleteUser: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/users/`,
		updateUser: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/users/`,
		createUser: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/users/`,
		lockUser: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/users/`,
		changePassword: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/users/`,
		getUserPermissions: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/users/get-all-permissions`,
		getInformation: `${process.env.NEXT_APP_IOT_DOMAIN}/api/abp/application-configuration`,
		getAvatar: `${process.env.NEXT_APP_IOT_DOMAIN}/api/account/profile-picture-file/`,
	},
	roleManagement: {
		getAllRoles: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/roles/all`,
		getRoleByUserID: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/users/`,
		getRole: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/roles/`,
		addNewRole: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/roles/`,
		updateRole: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/roles/`,
		deleteRole: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/roles/`,
	},
	permissionManagement: {
		getPermissions: `${process.env.NEXT_APP_IOT_DOMAIN}/api/permission-management/permissions`,
		updatePermissions: `${process.env.NEXT_APP_IOT_DOMAIN}/api/permission-management/permissions`,
	},
	securityLog: {
		getAllSecurityLog: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/security-logs`,
		getSecurityLog: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/security-logs/`,
		getMySecurityLog: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/security-logs/my`,
		getMySecurityLog_ID: `${process.env.NEXT_APP_IOT_DOMAIN}/api/identity/security-logs/my/`,
	},
	auditLogs: {
		getAllAuditLogs: `${process.env.NEXT_APP_IOT_DOMAIN}/api/audit-logging/audit-logs`,
		getAuditLogs: `${process.env.NEXT_APP_IOT_DOMAIN}/api/audit-logging/audit-logs/`,
		getAuditLogs_Errorrate: `${process.env.NEXT_APP_IOT_DOMAIN}/api/audit-logging/audit-logs/statistics/error-rate`,
		getAuditLogs_Average: `${process.env.NEXT_APP_IOT_DOMAIN}/api/audit-logging/audit-logs/statistics/average-execution-duration-per-day`,
		getAllAuditLogs_EntityChanges: `${process.env.NEXT_APP_IOT_DOMAIN}/api/audit-logging/audit-logs/entity-changes`,
		getAuditLogs_EntityChanges: `${process.env.NEXT_APP_IOT_DOMAIN}/api/audit-logging/audit-logs/entity-changes/`,
		getAllAuditLogs_EntityChanges_Username: `${process.env.NEXT_APP_IOT_DOMAIN}/api/audit-logging/audit-logs/entity-changes-with-username`,
		getAuditLogs_EntityChanges_Username: `${process.env.NEXT_APP_IOT_DOMAIN}/api/audit-logging/audit-logs/entity-changes-with-username/`,
	},
	abpConfiguration: {
		getAbpConfiguration: `${process.env.NEXT_APP_IOT_DOMAIN}/api/abp/application-configuration`,
	},
	dashboard: {
		getTurretAmount: `${process.env.NEXT_APP_IOT_DOMAIN}/api/Statistic/ChuSoHuu/thongke-soluong`,
		getStationQuantityByEnterprise: `${process.env.NEXT_APP_IOT_DOMAIN}/api/Statistic/ChuSoHuu/thongke-soluong-tram-tru-theochusohuu`,
		getSharedStationQuantity: `${process.env.NEXT_APP_IOT_DOMAIN}/api/Statistic/ChuSoHuu/thongke-tyle-tram-dungchung`,
		getStationQuantityByDistrict: `${process.env.NEXT_APP_IOT_DOMAIN}/api/Statistic/Country/thongke-tong-soluong-tram-tru`,
	},
	doanhnghiep: {
		getAllDoanhNghiep: `${process.env.NEXT_APP_IOT_DOMAIN}/api/BTS/DoanhNghiep/get-all-doanhNghiep-table`,
		createNewDN: `${process.env.NEXT_APP_IOT_DOMAIN}/api/app/doanh-nghiep`,
		editDN: `${process.env.NEXT_APP_IOT_DOMAIN}/api/app/doanh-nghiep/`,
		deleteDN: `${process.env.NEXT_APP_IOT_DOMAIN}/api/app/doanh-nghiep/`,
	},
	stationTypeManagement: {
		getStationType: `${process.env.NEXT_APP_IOT_DOMAIN}/api/app/loai-tram`,
		createStationType: `${process.env.NEXT_APP_IOT_DOMAIN}/api/app/loai-tram`,
		deleteStationType: `${process.env.NEXT_APP_IOT_DOMAIN}/api/app/loai-tram`,
		updateStationType: `${process.env.NEXT_APP_IOT_DOMAIN}/api/app/loai-tram`,
	},
	extendedDataLayer: {
		getExtendedDataLayer: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/quan-ly-du-lieu-mo-rongs/get-list-async`,
		getProperties: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/thuoc-tinh-mo-rong`,
		getListDataType: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/LayerDataType/get-list`,
		updateProperty: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/thuoc-tinh-mo-rong/update-async`,
		deleteProperty: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/detailActivity/check-delete-properties`,
		listDataAvailable: {
			propModals: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/prop-modals/get-list-async`,
			getAllDoanhNghiepTable: `${process.env.NEXT_APP_IOT_DOMAIN}/api/BTS/DoanhNghiep/get-all-doanhNghiep-table`,
			loaiTram: `${process.env.NEXT_APP_IOT_DOMAIN}/api/app/loai-tram`,
			loaiCaps: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/loai-caps`,
		},
	},
	stationManagement: {},
	typeManagement: {
		ownerManagement: {
			getAllOwners: `${process.env.NEXT_APP_IOT_DOMAIN}/api/app/chu-so-huu`,
			getAllOwnerStationCount: `${process.env.NEXT_APP_IOT_DOMAIN}/api/BTS/ChuSoHuu/count-chusohuu`,
			addNewOwner: `${process.env.NEXT_APP_IOT_DOMAIN}/api/app/chu-so-huu`,
			updateOwner: `${process.env.NEXT_APP_IOT_DOMAIN}/api/app/chu-so-huu`,
			deleteOwner: `${process.env.NEXT_APP_IOT_DOMAIN}/api/app/chu-so-huu`,
			getOwnerById: `${process.env.NEXT_APP_IOT_DOMAIN}/api/app/chu-so-huu`,
			getAllMembers: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/chu-so-huu-members/get-available-users`,
			getMembersByOwnerId: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/chu-so-huu-members/getMembers`,
			addMembers: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/chu-so-huu-members/addMembers`,
			deleteOwnerMember: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/chu-so-huu-members/removeMembers`,
		},
	},
	userClaim: {
		updateClaim: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/userClaim/updateClaimByUserChuSoHuu`,
	},
	file: {
		uploadImage: `${process.env.NEXT_APP_IOT_DOMAIN}/api/BTS/file/image`,
		uploadObject: `${process.env.NEXT_APP_IOT_DOMAIN}/api/BTS/file/object`,
	},
	image: `${process.env.IOT_STORAGE_DOMAIN}/data/image`,
	object3D: `${process.env.IOT_STORAGE_DOMAIN}/data/object`,
	images: {
		owner: {
			existing: `${process.env.CLOUD_IOT_DOMAIN}/images/ChuSoHuu`,
			planned: `${process.env.CLOUD_IOT_DOMAIN}/images/ChuSoHuu/KeHoach`,
			station: `${process.env.CLOUD_IOT_DOMAIN}/images/ChuSoHuu/NhaTram`,
		},
		object3D: `${process.env.CLOUD_IOT_DOMAIN}`,
	},
	cabTypeManagement: {
		getCabType: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/loai-caps`,
		createCabType: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/loai-caps`,
		deleteCabType: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/loai-caps`,
		updateCabType: `${process.env.NEXT_APP_IOT_DOMAIN}/api/management/loai-caps`,
	},
};

export default UrlConfig;
